### ISSUE TITLE
pip repo title

### ISSUE THREAD

**Issue by 1271** [manga-py/providers#2]
Any ideas?

I think about `crawler_providers`

P.S.
Oh. Hey guys :hand:

**Comment by eight04** [comment]
For consistency, I think it should be `manga_py_providers`.

**Comment by 1271** [comment]
Pip allows you to make one repository part of another
It might look like this:
`manga_py.providers`

But I do not know whether it is appropriate :)

https://github.com/manga-py/manga-py/issues/217#issuecomment-524644934

**Comment by eight04** [comment]
Do you mean [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/)?

I'm not sure if it is possible to make `manga_py` as a namespace and a module at the same time. Or do we want to rename the CLI and make `manga_py` a pure namespace?

**Comment by 1271** [comment]
> Do you mean namespace packages?

Yeah

> I'm not sure if it is possible 

Yes. Its possible:

https://pypi.org/project/zope/
https://pypi.org/project/zope.schema/

**Comment by 1271** [comment]
Ok. I just was not sure about your say.
Then let's do it

If you need any other endpoints from your provider, feel free to say this or add them yourself

Thanks

**Comment by gromenauer** [comment]
Seems fine to me.
Do we need to `pip install manga_py.providers` or will it come in `pip install --upgrade manga_py.providers` ?

**Comment by 1271** [comment]
@gromenauer nope
manga-py/requirements = [
...
manga-py.providers
...
]

**Comment by eight04** [comment]
> In the future, perhaps this will make it possible to implement the GUI version as well, if there is extra time

If the plugin system is set up, Comic Crawler will become the GUI of manga_py since it will use plugins from this repo.
