### ISSUE TITLE
What is the purpose of provider.html?

### ISSUE THREAD

**Issue by eight04** [manga-py/providers#6]
1. Why do we assign an `HtmlParser` instance to a provider? Shouldn't we `from ..utils.html_parser import HtmlParser`?
2. It seems that `HtmlParser` is a namespace of multiple static methods. Why do we initiate it as an instance? (`HtmlParser()`)

**Comment by 1271** [comment]
isinstance check only

**Comment by eight04** [comment]
Do you mean to make type-checking work on this line?
https://github.com/manga-py/providers/blob/29b22a7d9d452ee37cef5eefec7713866048fc70/manga_py/providers/utils/properties.py#L17

I think it makes more sense to avoid assigning a service as a plugin property. Especially when the service knows nothing about the plugin (i.e all plugins have the exactly same `HtmlParser` instance). I suggest something like:

*at the bottom of html_parser.py*
```py
html = HtmlParser()
```
*in the plugin*
```py
from ..utils.html_parser import html

  # in the hook
  def get_chapters(self):
      items = html.parse(self.content, '.table tr > td > a')
      # ...
```

**Comment by 1271** [comment]
Fixed. Covered in tests

**Comment by eight04** [comment]
> Html parser is used in 9/10 providers one way or another, so I see no reason to register import in each of them

When python imports modules, only one module instance will be loaded. If there are multiple providers do `from ..utils.html_parser import html`, each provider will get the exact same object (i.e. they have the same `id(html)`).

https://docs.python.org/3/tutorial/modules.html#more-on-modules

> Note For efficiency reasons, each module is only imported once per interpreter session. Therefore, if you change your modules, you must restart the interpreter – or, if it’s just one module you want to test interactively, use importlib.reload(), e.g. import importlib; importlib.reload(modulename).

There is no need to assign the object to the provider instance to make providers share the same object.

**Comment by eight04** [comment]
This also applies to `types.*`, `exceptions.*`, etc. They are imported with `import` statement, but all providers use the same object.

**Comment by 1271** [comment]
> When python imports modules

I know. I just don’t see the point in importing a module for each provider. I.e.


provider1.py
```python3
from ..utils.html_parser import html

class MyProvider1(): ...
```

provider2.py
```python3
from ..utils.html_parser import html

class MyProvider2(): ...
```

> They are imported with import statement, but all providers use the same object.

Yes. But is not it more convenient to write MyException () against exceptions.MyException ()?

**Comment by 1271** [comment]
If we import 1 function/class from a module, python will still access the whole module and put it into memory.
I don't see reason not to use the magic `from <module> import *`

**Comment by eight04** [comment]
I don't understand. Do you mean that you prefer `from ..exception import MyException` but against `from ..utils.html_parser import html`?

**Comment by 1271** [comment]
Oh. Sorry for my English.

I'm not against.

You mean that you should not assign BaseProvider services by default. Right?

**Comment by eight04** [comment]
> You mean that you should not assign BaseProvider services by default. Right?

Yes. I'm confused that why `_html` is a property of the provider. Unlike `_requests`, which is a service provided by the application (which is set inside `__init__()`). `_html` is just a static namespace. I don't see the reason to make it a property of the provider.

**Comment by 1271** [comment]
Well if you are so confused, can be removed.

**Comment by 1271** [comment]
The reason of adding the parser was that it adds the ability to overload it
For example:

```python
from .. import HtmlParser, get_provider

class MyParser (HtmlParser):
     def make_awesome(self):
         pass

provider = get_provider('http://manga ...')

provider.AUTO_INIT = False  # disable prepare() auto-call
provider.html = MyParser()  # replace default HtmlParser

 # init it manual
provider = provider()
provider.prepare()
provider.meta = provider.get_meta()

for chapter in provider.get_chapters():
   print(str(chapter))
```

**Comment by eight04** [comment]
Then I think it should be passed to `__init__` just like `connection`. There should only be one way to override a service.

**Comment by 1271** [comment]
I thought about it, yes.
Ok, I’ll do it. thanks
